### ISSUE TITLE
License not specified for these icons

### ISSUE THREAD

**Issue by pramilo** [pasnox/oxygen-icons-png#1]
Hi

Can you please clarify what is the license for this particular Iconset?

The one downloadable form Archlinux is LGPL; however, based on the README file that accompanies these icons, it hints they may have a more permissive license.

Can you please clarify?

Thank you

**Comment by pasnox** [comment]
Hi. That s clearly original licence coming with oxygen theme itself. I will update the readme to be consistent.

**Comment by jschnasse** [comment]
+1

**Comment by pasnox** [comment]
Updated readme to explictly say it use original license which is LGPL.
