### ISSUE TITLE
Unpacked package file from download link is "damaged and can't be opened"

### ISSUE THREAD

**Issue by brunzino** [pasnox/oxygen-icons-png#2]
Following the archlinux.org link in the README page downloads a tar.xz of the pkg file. After unpacking the download with Archive Utility on OS X, I attempt to open the install the pkg and it delivers a message that `“oxygen-icons-15.04.3-1-any.pkg” is damaged and can’t be opened. You should move it to the Trash.`

Opening with the Unarchiver software works, however.

**Comment by pasnox** [comment]
That's an ArchLinux package, not an OSX one.
Even though they both ends with .pkg, they are not the same things.
OSX is just thinking it's an osx package, but it's really not.
The correct way to uncompress that on OSX is to use command line or 3rdparty uncompressor like said 'The Unarchiver'.
